version: '3'

services:
  redis-master:
    image: redis:7
    container_name: redis-master
    ports:
      - "6379:6379"
    volumes:
      - ./conf/master.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  redis-slave1:
    image: redis:7
    container_name: redis-slave1
    ports:
      - "6380:6379"
    depends_on:
      - redis-master
    volumes:
      - ./conf/slave1.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  redis-slave2:
    image: redis:7
    container_name: redis-slave2
    ports:
      - "6381:6379"
    depends_on:
      - redis-master
    volumes:
      - ./conf/slave2.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  haproxy:
    image: haproxy:latest
    container_name: redis-haproxy
    ports:
      - "7000:7000"
    volumes:
      - ./conf/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
